### ISSUE TITLE
cannot compile with ghc-9.10 because `forall` becomes reserved

### ISSUE THREAD

**Issue by jwaldmann** [hguenther/smtlib2#26]
with ghc-9.10.1-alpha-1 and head.hackage,

```
Building library for smtlib2-1.0...                      
                                                                                                                                  
Language/SMTLib2.hs:55:11: error: [GHC-58481]      
    parse error on input ‘forall’               
   |                                                             
55 |   exists, forall,                                           
   |           ^^^^^^

Language/SMTLib2/Internals/Interface.hs:9:16: error: [GHC-58481]
    parse error on input ‘forall’
  |
9 |         exists,forall,
  |                ^^^^^^
Error: [Cabal-7125]
```
I think the recommended work-around is to rename to `forall_` (...  should be `for_all` for much better optics)
